layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: mojtaba_khomami
  # keybase: your_username
  linkedin: mojtaba-khomami-abadi
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: mojtabakhomami
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Passion
    web_url: https://https://stratuscent.com/
    image_url: https://pbs.twimg.com/profile_images/1214965323004338176/oPijMQrF_400x400.jpg

  - name: Patents
    web_url: https://patents.google.com/?inventor=khomami+abadi
    image_url: https://static.scientificamerican.com/sciam/cache/file/987F7B3E-85C1-47D6-91416FCA62F71B37_source.jpg?w=590&h=800&BCC79672-80B4-48EE-88312A4341E6530E

  - name: Google Scholar
    web_url: https://scholar.google.it/citations?user=iMn11ZkAAAAJ&hl=en
    image_url: https://gcgosling.files.wordpress.com/2012/10/google-scholar-logo.png?w=256

theme: jekyll-theme-minimal